# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.cache/wt} [current_project]
set_property parent.project_path {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {d:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/new/Adder_3_Bit.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/imports/new/Decoder_2_to_4.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/imports/new/Decoder_3_to_8.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/imports/new/FA.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/imports/new/HA.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/new/Instruction_Decoder.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/imports/Lab Work/Lab_7/Lab_7.srcs/sources_1/new/LUT_16_7.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/new/LUT_7_12.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/new/MUX_2_1_3Bit.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/new/MUX_2_1_4Bit.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/new/MUX_8_1_4Bit.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/imports/new/Mux_8_to_1.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/new/Program_Counter_3Bit.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/imports/new/RCA_4.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/new/Reg_4Bit.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/new/Reg_Bank.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/imports/new/Slow_Clk.vhd}
  {D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/sources_1/new/CPU.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/constrs_1/imports/Lab Work/Basys3Labs.xdc}}
set_property used_in_implementation false [get_files {{D:/Academic/02. Computer Organization and Digital Design/Lab Work/Nano_Processor/Nano_Processor.srcs/constrs_1/imports/Lab Work/Basys3Labs.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top CPU -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
